import express from 'express';
import controll from "../control/controlLogin.js";
import controlA from "../control/ControlAgent.js";
import controlD from  "../control/controlDossie.js";
import PDFController  from "../control/PDFController.js";
import Plan  from "../control/controlP.js";
import stat  from "../control/staticMcontrol.js";

const router = express.Router();
router.post("/api/profil", controll.ajouterProfil);
router.delete("/api/supProfil", controll.DeletProfil);
router.post("/api/login", controll.verficontrol);
router.post("/api/password", controll.updatePassword);
router.get("/api/selProfil", controll.getProfils);
router.post("/api/statut", controll.changeStatut);
router.put("/api/modifieProfil", controll.updateProfil);
router.post("/api/ajouter", controlA.InsertAgentAndPoste);
router.get("/api/agentall", controlA.selctALLagent);
router.post("/api/agent1", controlA.selectAgent);
router.get("/api/agent2", controlA.selctAgent2);
router.delete("/api/supagent/:IdA", controlA.deleteAgent);
router.put("/api/modifagent", controlA.updateAgentAndPoste);
router.post("/api/convocation", controlA.envoyerEmailEtInsert); 
router.post("/api/selctRdv",controlA.selcectRdv); 
router.delete("/api/suprdv/:IdR", controlA.deleteRdv);
router.put("/api/modifRdv", controlA.updateRdv);
router.post("/api/visiteP", controlA.insererVisiteP);
router.post("/api/visitePDeJour", controlA.getVisitesDuJourP);
router.put("/api/modifierVisiteP", controlA.modifierVisiteP);
router.delete("/api/supvisiteP/:IdV", controlA.supprimerPrepareVisite);
router.post("/api/Cardiovasculaire",controlD.insertCardiovasculaire) ;
router.post("/api/Digestif",controlD.insertDigestif) ;
router.post("/api/Endocrino",controlD.insertEndocrino) ;
router.post("/api/ExemensComplementaires",controlD.insertExemensComplementaires) ;
router.post("/api/Explorationsfonctionnelles",controlD.insertExplorationsfonctionnelles) ;
router.post("/api/genitourinair",controlD.insertgenitourinair) ;
router.post("/api/hematogg",controlD.inserthematogg);
router.post("/api/locomoteur",controlD.insertlocomoteur);
router.post("/api/neuropsychisme",controlD.insertneuropsychisme);
router.post("/api/opht",controlD.insertopht);
router.post("/api/orl",controlD.insertorl);
router.post("/api/peaumuqueuses",controlD.insertpeaumuqueuses);
router.post("/api/respiratoire",controlD.insertrespiratoire);
router.post("/api/donnee",controlA.ajouterDonnees);
// router.post("/api/examenbiologique",controlA.ajouterexamenbiologique);
// router.post("/api/examenradio",controlA.ajouterradio);
// router.post("/api/medicament",controlA.ajoutermedicament);
router.post('/api/ordordenence', PDFController.createPDF);
router.post('/api/BonS', PDFController.getCertificate);
router.get('/api/plan', Plan.getPlaning);
router.post('/api/stat', stat.getMonthlyStatistics);
// router.post('/api/dossie', controlA.ajouterResulta); 
router.post('/api/VisitP', controlA.getDetails); 

 
export default router;  
 